// One table for every native surface (menu bar, tray) so a language never
// exists on one and not the other.
pub struct MenuLabels {
    pub settings: &'static str,
    pub new_message: &'static str,
    pub sync_all: &'static str,
    pub reply: &'static str,
    pub reply_all: &'static str,
    pub forward: &'static str,
    pub file: &'static str,
    pub edit: &'static str,
    pub mailbox: &'static str,
    pub message: &'static str,
    pub window: &'static str,
    pub show: &'static str,
    pub quit: &'static str,
    pub archive: &'static str,
    pub mark_read: &'static str,
    pub task_due: &'static str,
    pub task_mark_done: &'static str,
}

pub fn for_lang(lang: &str) -> MenuLabels {
    match lang {
        "de" => MenuLabels {
            settings: "Einstellungen…",
            new_message: "Neue E-Mail",
            sync_all: "Alle Konten abrufen",
            reply: "Antworten",
            reply_all: "Allen antworten",
            forward: "Weiterleiten",
            file: "Ablage",
            edit: "Bearbeiten",
            mailbox: "Postfach",
            message: "E-Mail",
            window: "Fenster",
            show: "Prudii Mail anzeigen",
            quit: "Beenden",
            archive: "Archivieren",
            mark_read: "Als gelesen markieren",
            task_due: "Aufgabe fällig",
            task_mark_done: "Erledigt",
        },
        "es" => MenuLabels {
            settings: "Configuración…",
            new_message: "Nuevo mensaje",
            sync_all: "Recibir todo el correo nuevo",
            reply: "Responder",
            reply_all: "Responder a todos",
            forward: "Reenviar",
            file: "Archivo",
            edit: "Edición",
            mailbox: "Buzón",
            message: "Mensaje",
            window: "Ventana",
            show: "Mostrar Prudii Mail",
            quit: "Salir",
            archive: "Archivar",
            mark_read: "Marcar como leído",
            task_due: "Tarea vencida",
            task_mark_done: "Hecho",
        },
        "fr" => MenuLabels {
            settings: "Paramètres…",
            new_message: "Nouveau message",
            sync_all: "Relever tout le courrier",
            reply: "Répondre",
            reply_all: "Répondre à tous",
            forward: "Transférer",
            file: "Fichier",
            edit: "Édition",
            mailbox: "Boîte aux lettres",
            message: "Message",
            window: "Fenêtre",
            show: "Afficher Prudii Mail",
            quit: "Quitter",
            archive: "Archiver",
            mark_read: "Marquer comme lu",
            task_due: "Tâche échue",
            task_mark_done: "Terminé",
        },
        "pt" => MenuLabels {
            settings: "Configurações…",
            new_message: "Nova Mensagem",
            sync_all: "Receber Todas as Mensagens",
            reply: "Responder",
            reply_all: "Responder a Todos",
            forward: "Encaminhar",
            file: "Arquivo",
            edit: "Edição",
            mailbox: "Caixa de Correio",
            message: "Mensagem",
            window: "Janela",
            show: "Mostrar Prudii Mail",
            quit: "Sair",
            archive: "Arquivar",
            mark_read: "Marcar como lido",
            task_due: "Tarefa vencida",
            task_mark_done: "Concluída",
        },
        "ru" => MenuLabels {
            settings: "Настройки…",
            new_message: "Новое письмо",
            sync_all: "Получить всю новую почту",
            reply: "Ответить",
            reply_all: "Ответить всем",
            forward: "Переслать",
            file: "Файл",
            edit: "Правка",
            mailbox: "Почтовый ящик",
            message: "Сообщение",
            window: "Окно",
            show: "Показать Prudii Mail",
            quit: "Выход",
            archive: "В архив",
            mark_read: "Пометить прочитанным",
            task_due: "Задача просрочена",
            task_mark_done: "Готово",
        },
        "zh" => MenuLabels {
            settings: "设置…",
            new_message: "新邮件",
            sync_all: "接收全部新邮件",
            reply: "回复",
            reply_all: "全部回复",
            forward: "转发",
            file: "文件",
            edit: "编辑",
            mailbox: "邮箱",
            message: "邮件",
            window: "窗口",
            show: "显示 Prudii Mail",
            quit: "退出",
            archive: "归档",
            mark_read: "标为已读",
            task_due: "任务到期",
            task_mark_done: "完成",
        },
        _ => MenuLabels {
            settings: "Settings…",
            new_message: "New Message",
            sync_all: "Get All New Mail",
            reply: "Reply",
            reply_all: "Reply All",
            forward: "Forward",
            file: "File",
            edit: "Edit",
            mailbox: "Mailbox",
            message: "Message",
            window: "Window",
            show: "Show Prudii Mail",
            quit: "Quit",
            archive: "Archive",
            mark_read: "Mark as read",
            task_due: "Task due",
            task_mark_done: "Done",
        },
    }
}
